name: First Workflow
on: workflow_dispatch # Allows manual triggering of workflow
jobs:
  first-job: 
    runs-on: ubuntu-latest
    steps:
      - name: Print Greeting
        run: echo "Hello World!"
      - name: "Print goodbye"
        run: echo "Done, bye"
